### ISSUE TITLE
Change Language not saved [BUG]

### ISSUE THREAD

**Issue by xadowtek** [Guilouz/KlipperScreen-Flsun-Speeder-Pad#11]
**Describe the bug**
If i change Klipperscreen language to another (not english), and then restart the pad, automatically restart language to 
default english.

**To Reproduce**
1. Go to 'Settings
2. Click on "change language"
4. Choose another language (no english, of course)
5. Click save config, or not (It doesn't matter)
6. Restart Speeder pad
7. English language again (not save changes)

**Expected behavior**
Save language changes.
I try to find in KlipperScreen.conf some settings, but doesn't appear nothing related to language.

**Logfile**
Attach your [klipperscreen.log]

[KlipperScreen.log](https://github.com/Guilouz/KlipperScreen-Flsun-Speeder-Pad/files/11817207/KlipperScreen.log)

**Comment by Guilouz** [comment]
Update to latest version, it's already fixed.
