### ISSUE TITLE
Does not update z_offset in the variables file any longer.

### ISSUE THREAD

**Issue by CaryBab** [Guilouz/KlipperScreen-Flsun-Speeder-Pad#13]
**Describe the bug**
When I first installed speederpad software in March, setting the z_offset worked great.  When I went to do it today, it leaves it set to 0.
Thinking maybe I had done something to cause this, I completely rebuilt my speederpad from scratch going through you complete wiki install instructions.  Trying it again, it still does not set it.

**To Reproduce**
Choose to set z_offset, perform the paper test, press accept, and then continue to perform the save.

**Expected behavior**
I expected it to set my z_offset in the variables.cfg file, and to show up on my z_offset on my screen instead of zero.

**Screenshots**

**Logfile**
Attach your [klipperscreen.log](https://klipperscreen.readthedocs.io/en/latest/Troubleshooting/)
[klippy.log](https://github.com/Guilouz/KlipperScreen-Flsun-Speeder-Pad/files/11872488/klippy.log)

**Comment by Guilouz** [comment]
Do not confuse Z-Offset and Gcode Offset.

The Z-Offset is measured during the probe offset and is saved in the printer.cfg. Only the gcode offset is saved in the variables.cfg file which corresponds to the babystep.

**Comment by CaryBab** [comment]
Are there any logs I can send you.  They are fairly clean since I did a
complete re-install.

**Comment by Guilouz** [comment]
No need to send me a log, what you explain is normal. 
The Z-offset will never be saved in the variables.cfg file. This value is saved in the printer.cfg following the measurement via the Z_OFFSET_CALIBRATION macro.
Only the difference given via babystep will be saved in the variables.cfg as gcode offset.

**Comment by Guilouz** [comment]
With paper test it's z offset that is mesured and it saved to printer.cfg file not in variables.cfg, this is not babystep.

**Comment by CaryBab** [comment]
I'm confused then, that is what I did before when it saved it.  How am I
suppose to be doing it.  Sorry, I thought I was doing it correctly.

**Comment by CaryBab** [comment]
2:00 PM
Loaded Z-Offset from variables.cfg file: {'z': '0'}
2:00 PM
Klipper state: Disconnect
2:00 PM
SAVE_CONFIG
2:00 PM
probe: z_offset: 5.701
The SAVE_CONFIG command will update the printer config file
with the above and restart the printer.
2:00 PM
G28
2:00 PM
ACCEPT
2:00 PM
Z position: 1.936 --> 2.036 <-- 2.136
2:00 PM
TESTZ Z=+.1
2:00 PM
Z position: 1.736 --> 1.936 <-- 2.036
2:00 PM
TESTZ Z=-.1
1:59 PM
Z position: 1.736 --> 2.036 <-- 2.136
1:59 PM
TESTZ Z=-.1
1:59 PM
Z position: 1.736 --> 2.136 <-- 2.236
1:59 PM
TESTZ Z=-.1
1:59 PM
Z position: 1.736 --> 2.236 <-- 2.736
1:59 PM
TESTZ Z=-.5
1:59 PM
Z position: 1.736 --> 2.736 <-- 7.736
1:59 PM
TESTZ Z=+1
1:59 PM
Z position: ?????? --> 1.736 <-- 2.736
1:59 PM
TESTZ Z=-1
1:59 PM
Z position: ?????? --> 2.736 <-- 7.736
1:59 PM
TESTZ Z=-5
1:59 PM
Z position: ?????? --> 7.736 <-- 12.736
1:59 PM
TESTZ Z=-5
1:59 PM
Z position: ?????? --> 12.736 <-- ??????
1:59 PM
Starting manual Z probe. Use TESTZ to adjust position.
Finish with ACCEPT or ABORT command.

**Comment by Guilouz** [comment]
Calibration must be done like this : 

- Mesure Probe Offset (Z-Offset) with Z_OFFSET_CALIBRATION macro and paper, this will have the action of defining the z offset in the printer.cfg file.
- Start Endstop Calibration with ENDSTOPS_CALIBRATION macro.
- Start Delta Calibration with DELTA_CALIBRATION macro.
- Start Bed Leveling with BED_LEVELING macro.
- Optional you can also apply a 2mm Safety Offset with SECURITY_OFFSET macro. This will have the action of defining a gcode offset of 2mm above the measured value during the Probe Offset, to avoid scratching the plate if the measured value is not perfect.

When it's done start a print and check your first layer by adjusting the babysteps. And it is this value (the difference from the actual Z Offset) that will be saved in the variables.cfg file.

**Comment by CaryBab** [comment]
Ahh, I will give that a shot.  Thanks
