### ISSUE TITLE
z_offset accounting for probe sensor height

### ISSUE THREAD

**Issue by CaryBab** [Guilouz/KlipperScreen-Flsun-Speeder-Pad#15]
As can be seen from my console log below the probe sees a z height of 8.1875, and when it goes to the TESTZ section it is now 13.186, I subtract 1mm and it is 12.186, but then when I ACCEPT it is now -3.999.

Is this somewhere it the code subtracting the height of the probe ?

Can this be a variable set in the printer.cfg file ?

I don't understand the height changes going on.

I tried a facebook post, but nobody is even reading it, their just saying whatever they think I'm asking from the subject matter.

Sorry again for this if its not something that can be done, but you seem to be the only one that knows how anything works.

**** excerpt from my console ***
probe: z_offset: -3.999
The SAVE_CONFIG command will update the printer config file
with the above and restart the printer.
ACCEPT
Z position: ?????? --> 12.186 <-- 13.186
TESTZ Z=-1
Z position: ?????? --> 13.186 <-- ??????
Starting manual Z probe. Use TESTZ to adjust position.
Finish with ACCEPT or ABORT command.
probe at 0.000,0.000 is z=8.175000
probe at 0.000,0.000 is z=8.187500
probe at 0.000,0.000 is z=8.187500
Z_OFFSET_CALIBRATION

**Comment by Guilouz** [comment]
Please don't post Issue for other thing is not related to KlipperScreen.

It's how Klipper works.

**Comment by CaryBab** [comment]
Ok, sorry I've donated to you twice now, won't happen again.

**Comment by Guilouz** [comment]
Issues are made to report a bug on the repo application, this is not a discussion forum.

For that there is the discussion on the speeder pad repo here: https://github.com/Guilouz/Klipper-Flsun-Speeder-Pad/discussions

**Comment by CaryBab** [comment]
Thanks, I'll look at that and maybe put my query there.
