### ISSUE TITLE
[BUG]  The main layer count it is not working

### ISSUE THREAD

**Issue by cpasoft** [Guilouz/KlipperScreen-Flsun-Speeder-Pad#16]
**Describe the bug**
The layer count on the main screen is not working. If you enter for details, then it shows right...

**To Reproduce**
I've uploaded a video 

**Minivideo**
https://github.com/Guilouz/KlipperScreen-Flsun-Speeder-Pad/assets/29692062/676a984e-2276-474c-95e6-ea6b87e44fae

**Screenshot of versions**
![imagen](https://github.com/Guilouz/KlipperScreen-Flsun-Speeder-Pad/assets/29692062/ca522f5e-a19c-4811-9762-d66c63acdc95)

**Comment by Guilouz** [comment]
Normaly it's fixed in last version.
