### ISSUE TITLE
no camera after installing the official versions

### ISSUE THREAD

**Issue by JYCrois** [Guilouz/KlipperScreen-Flsun-Speeder-Pad#17]
Thank you for this great tutorial.
Everything went fine except for the camera.
as soon as I remove the Flsun builds and install the official builds (1 instance), I lose the camera.
I reinstalled 3 times and still the same problem.
I searched the web and I'm not the only one having this problem.
So forced to reinstall the construction of Flsun, too bad!
![Capture d'écran 2023-08-11 151132](https://github.com/Guilouz/KlipperScreen-Flsun-Speeder-Pad/assets/116349530/0e4e01d8-7b50-4c30-bace-f9e85438cfe0)
![Capture d'écran 2023-08-11 153238](https://github.com/Guilouz/KlipperScreen-Flsun-Speeder-Pad/assets/116349530/5a0e4f84-a8f4-42be-898a-bf87f8835733)

**Comment by Guilouz** [comment]
It's an installation issue and not related to this repo (Klipperscreen).
