### ISSUE TITLE
M600 if you wait too long to change filament then it heats up, loads filament, goes to print and immediately does another filament change

### ISSUE THREAD

**Issue by CaryBab** [Guilouz/KlipperScreen-Flsun-Speeder-Pad#18]
**Describe the bug**
M600 if you wait too long to change filament then it heats up, loads filament, goes to print and immediately does another filament change.
**To Reproduce**
Code a M600 in your gcode.
Wait, I'm going to guess 1800 seconds
Change filament

**Expected behavior**
Do not expect it to immediatelly do another filament change

**Screenshots**
17:57:08
echo: Resuming printing...
17:56:57
echo: Loading filament...
17:56:52
echo: Nozzle heating...
17:56:52
idle_timeout: Timeout set to 1800.00 s
17:56:52
probe: TRIGGERED
17:56:42
echo: Nozzle heating stopped!
17:56:32
echo: Unloading filament...
17:56:28
Print already paused
17:56:28
echo: Pausing printing...
17:56:28
echo: Pausing printing...
17:56:28
idle_timeout: Timeout set to 86400.00 s
17:56:27
echo: Pausing printing...
17:56:26
echo: Resuming printing...
17:56:17
echo: Loading filament...
17:53:33
echo: Nozzle heating...
17:53:33
idle_timeout: Timeout set to 1800.00 s
17:53:33
probe: TRIGGERED
13:16:50
echo: Nozzle heating stopped!
13:16:41
echo: Unloading filament...
13:16:37
echo: Pausing printing...
13:16:36
echo: Pausing printing...
13:16:36
idle_timeout: Timeout set to 86400.00 s

**Logfile**
Attach your [klipperscreen.log](https://klipperscreen.readthedocs.io/en/latest/Troubleshooting/)

**Comment by Guilouz** [comment]
By default timeout is set to 1800s, then when printer enter in M600 mode timeout is set to 86400s (i.e. 24 hours) and when printer restart printing timeout is set by default at 1800s.

Like what I see in your log, i didn't see any issue.

**Comment by Guilouz** [comment]
And this repo is for Klipperscreen, so it's not related.

**Comment by CaryBab** [comment]
This is a problem in the PAUSE function of the MACRO.cfg, I think if you move the TIMEOUT=1800 under the ELSE statement where it checks to see if you are in the M600 option.

**Comment by Guilouz** [comment]
Make sure you use M600 function correctly:

When the M600 command is present in the Gcode file or when the end of filament detector is triggered, M600 macro is loaded.

The hotend will park towards the front of the printer.

The extruder will then extract the filament from the hotend and cut off the heating of the nozzle (in order to avoid continuous heating without extrusion if you are not in front of the printer at this time). Only the heating of the plate is maintained to avoid the detachment of the model.

From this moment the printer remains in stand-by (for 86400s before cutting off the heating of the bed and deactivating the motors) while waiting for an action from the user.

Then just come and place the new filament at the entrance of the extruder (and not insert it manually into the hotend) and resume printing. It is important not to click the resume button multiple times.

The nozzle will then resume heating to the initial printing temperature.

Once the heating is reached, the extruder will then load the new filament and then perform a purge of a few centimeters.

Printing is then restarted.

**Comment by CaryBab** [comment]
Yes, I do a bunch of filament changes in my printing.  The first time it
happened I thought maybe I had pressed the resume button more than once,
but then I thought about it, and if I had done that it would have just
paused instead of doing a filament change.

So I made the modification last night to move the "timeout=1800" into the
else section of the pause, I let it sit in the filament change condition
overnight, changed the filament this morning, and it worked like it
should.  I suspect by putting the timeout=1800 in, since it had already
been over 1800 seconds, it immediately took affect.  But I shall see, since
as I said I do a lot of filament changes.

Thanks for your help.

**Comment by Guilouz** [comment]
You mean resume macro no ?

Like this:

[gcode_macro RESUME]
description: Resume the current print
rename_existing: RESUME_BASE
gcode:
  ##### set defaults #####
  {% set e = params.E|default(1) %}
  #### get VELOCITY parameter if specified ####
  {% if 'VELOCITY' in params|upper %}
  {% set get_params = ('VELOCITY=' + params.VELOCITY)  %}
  {%else %}
  {% set get_params = "" %}
  {% endif %}
  ##### end of definitions #####
  G91
  {% if printer["gcode_macro M600"].m600_enabled == 1 %}
  RESPOND MSG="Nozzle heating..."
  M109 S{printer["gcode_macro M600"].hotend_temp}
  RESPOND MSG="Loading filament..."
  G0 E50 F800
  G0 E30 F300
  M400
  M106 S255
  SET_GCODE_VARIABLE MACRO=M600 VARIABLE=m600_enabled VALUE=0
  {% else %}
  SET_IDLE_TIMEOUT TIMEOUT=1800
  G1 E{e} F2100
  {% endif %}
  RESPOND MSG="Resuming printing..."
  RESUME_BASE {get_params}

**Comment by CaryBab** [comment]
Exactly what I did, and that seems to fix it.

**Comment by CaryBab** [comment]
What I suspect is because the printer still is in the pause state when you
set it to a time that has already expired it finishes what it is doing.
What I don't quite understand is why instead of just doing a normal PAUSE,
it does another M600.

**Comment by Guilouz** [comment]
Can you try this one, because timeout need to be restored after a M600:

```
[gcode_macro RESUME]
description: Resume the current print
rename_existing: RESUME_BASE
gcode:
  ##### set defaults #####
  {% set e = params.E|default(1) %}
  #### get VELOCITY parameter if specified ####
  {% if 'VELOCITY' in params|upper %}
  {% set get_params = ('VELOCITY=' + params.VELOCITY)  %}
  {%else %}
  {% set get_params = "" %}
  {% endif %}
  ##### end of definitions #####
  G91
  {% if printer["gcode_macro M600"].m600_enabled == 1 %}
  RESPOND MSG="Nozzle heating..."
  M109 S{printer["gcode_macro M600"].hotend_temp}
  RESPOND MSG="Loading filament..."
  G0 E50 F800
  G0 E30 F300
  M400
  M106 S255
  SET_GCODE_VARIABLE MACRO=M600 VARIABLE=m600_enabled VALUE=0
  {% else %}
  G1 E{e} F2100
  {% endif %}
  SET_IDLE_TIMEOUT TIMEOUT=1800
  RESPOND MSG="Resuming printing..."
  RESUME_BASE {get_params}
```

**Comment by CaryBab** [comment]
I understand your concern, but I suspect because it hasn't actually resumed
at that point, it will pause again.  But I will give it a shot,  I won't be
able to try it until tomorrow morning after it does a filament change after
I'm in bed.

**Comment by CaryBab** [comment]
I think your concern is to have it set to 1800 during a normal pause,
correct ?  So maybe add it to the PAUSE code instead of the end of the
RESUME ?

**Comment by CaryBab** [comment]
By the way. I LOVE your temperature resume code.  Makes the wait so much
more pleasant.

**Comment by CaryBab** [comment]
Putting the timeout there seemed to work, but it did something it's never
done before.  It shut the motors off, so when I went to load the filament
the head moved.  It let me home it, and then it resumed, but at least it
did not go into another filament switch.

Thanks, Cary

**Comment by CaryBab** [comment]
Found the problem with the motors turning off.  It was ME.

**Comment by Guilouz** [comment]
So macros are correct as they are, right ?

**Comment by CaryBab** [comment]
Yes, but I moved it after the message of resuming printing just to give it
as much time to restart as possible.

**Comment by Guilouz** [comment]
1800s is 30min and 86400s is 24h so it's impossible after 2h resuming is done.

In your log all is set as expected, timeout 86400 is set when M600 is called and reverted to 1800 when resuming.

**Comment by CaryBab** [comment]
It did it again, and I finally found it in the Klipperscreen log, what
happened.
Hopefully you will know what is going on after seeing this.  Thanks.

Normal:
2023-08-27 17:15:49,341 [screen.py:show_popup_message()] - echo: Loading
filament...
2023-08-27 17:15:58,924 [screen.py:show_popup_message()] - echo: Resuming
printing...
2023-08-27 17:15:59,090 [printer.py:change_state()] - Changing state from
'paused' to 'printing'
2023-08-27 17:15:59,090 [printer.py:change_state()] - Adding callback for
state: printing
2023-08-27 17:15:59,100 [job_status.py:set_state()] - Changing job_status
state from 'paused' to 'printing'
2023-08-27 17:15:59,147 [screen.py:show_panel()] - Reinitializing panel
2023-08-27 17:15:59,279 [job_status.py:create_status_grid()] - Titlebar
items: ['']
2023-08-27 17:15:59,316 [screen.py:attach_panel()] - Current panel
hierarchy: job_status
2023-08-27 17:15:59,325 [job_status.py:set_state()] - Changing job_status
state from 'standby' to 'printing'

When it does another M600:
2023-08-27 19:39:08,278 [screen.py:show_popup_message()] - echo: Loading
filament...
2023-08-27 19:39:17,900 [screen.py:show_popup_message()] - echo: Resuming
printing...
2023-08-27 19:39:17,950 [screen.py:show_popup_message()] - echo: Pausing
printing...
2023-08-27 19:39:19,567 [screen.py:show_popup_message()] - echo: Pausing
printing...
2023-08-27 19:39:23,380 [screen.py:show_popup_message()] - echo: Unloading
filament...
2023-08-27 19:39:32,132 [screen.py:show_popup_message()] - echo: Nozzle
heating stopped!
