### ISSUE TITLE
[BUG] "No Xvideo support found." message when exiting from webcam-viewer

### ISSUE THREAD

**Issue by lmonterz** [Guilouz/KlipperScreen-Flsun-Speeder-Pad#19]
**Describe the bug**
Exiting from the webcam-viewer, for a fraction of second the system displays the error message "No Video support found."

**To Reproduce**
1. Go to the Webcam in the Configuration panel;
2. Exit from the webcam-viewer by tapping on the screen;
4. See error "No Xvideo support found." in the upper portion of the screen.

**Expected behavior**
Return to the Configuration menu without errors.

**Screenshots**
![5c94a7fd-669e-4b57-b175-77eacea24449](https://github.com/Guilouz/KlipperScreen-Flsun-Speeder-Pad/assets/45309224/5b71023d-24f6-4a58-8eb9-fb0c2e7d0f2e)

**Logfile**
Attach your [klipperscreen.log](https://klipperscreen.readthedocs.io/en/latest/Troubleshooting/)
[KlipperScreen.log](https://github.com/Guilouz/KlipperScreen-Flsun-Speeder-Pad/files/12389206/KlipperScreen.log)

**Comment by Guilouz** [comment]
Yes it's a KlipperScreen issue since recent change with camera support. Already reported.
