### ISSUE TITLE
[BUG] The layer field it is still not working. Reopen Issue #16

### ISSUE THREAD

**Issue by cpasoft** [Guilouz/KlipperScreen-Flsun-Speeder-Pad#21]
This issue still exists
https://github.com/Guilouz/KlipperScreen-Flsun-Speeder-Pad/issues/16

I've added the layer progress as advised in the Klipper screen documentation, and you'll see that it appears at the top of the main page with the correct counter. It is also fine on the details page, but not in the layer section.
![imagen](https://github.com/Guilouz/KlipperScreen-Flsun-Speeder-Pad/assets/29692062/268ab7b3-022d-401c-82a4-6b358a8c872c)

Here is a video where you can see the problem:
https://github.com/Guilouz/KlipperScreen-Flsun-Speeder-Pad/assets/29692062/e37e5cd1-5893-46de-9df9-12aec33e5291

I do NOT know how this field is calculated. The only thing I can think of that might affect it is that I use 64 microsteps in the stepper motors.

If you need any further information, just ask for it.

**Comment by cpasoft** [comment]
I'm thinking the problem is coming from this piece of code:
![imagen](https://github.com/Guilouz/KlipperScreen-Flsun-Speeder-Pad/assets/29692062/f0840309-11c1-43af-9897-8b8e35b68df6)

This piece of code does not appear in the original klipperscreen code.
You should get the data, not by calculating the height (which also works badly), but by the value sent by SET_PRINT_STATS_INFO CURRENT_LAYER AND TOTAL_LAYER, as recommended in the klipperscreen documentation.

**Comment by cpasoft** [comment]
I think the correct code to calculate the layer height is the one between lines 610 and 624, but then it is overwritten with the code I put above, which I think is not correct.

**Comment by cpasoft** [comment]
@Guilouz I have found that it fails when you have the z hop type of the retractions set to Slope or Spiral. If you set it to Normal, it doesn't fail...

![imagen](https://github.com/Guilouz/KlipperScreen-Flsun-Speeder-Pad/assets/29692062/6ae8c0bc-b50b-4c72-918a-a8c89bba6c9d)

I don't understand why this is happening and it has blown my mind. Hopefully this will give you a clue to try and fix it.

**Comment by cpasoft** [comment]
I don't understand how you systematically close this issue if it is not fixed.

Tested with the latest version (v0.3.7-13-g3fafe7aa) and it still failing in the same way. The moment you have Z hop type activated in slope mode, the layer counter fails.

**Comment by cpasoft** [comment]
Here you can see the real layer (via M117 command) and the layer displayed by KS.
![imagen](https://github.com/Guilouz/KlipperScreen-Flsun-Speeder-Pad/assets/29692062/25ccc38d-2cb0-4801-9442-3193bf343ca6)

**Comment by Guilouz** [comment]
That info is not provided by Moonraker and currently is calculated from the Z position.

The only way you will have what you want is if you do the [trick described in the docs](https://klipperscreen.readthedocs.io/en/latest/Quicktips/#layer-progress), and that method is the only one that works with the adaptive layers and unconventional Z Hop.

With the issue you mention, as it may not be accurate, I will remove it from the main status page and I would only keep it in the submenu of the job_status.

**Comment by cpasoft** [comment]
> That info is not provided by Moonraker and currently is calculated from the Z position.
> 
> The only way you will have what you want is if you do the [trick described in the docs](https://klipperscreen.readthedocs.io/en/latest/Quicktips/#layer-progress), and that method is the only one that works with the adaptive layers and unconventional Z Hop.
> 
> With the issue you mention, as it may not be accurate, I will remove it from the main status page and I would only keep it in the submenu of the job_status.

But It's working well on the layer info screen, as you can see in this video:

https://github.com/Guilouz/KlipperScreen-Flsun-Speeder-Pad/assets/29692062/612fa0ed-35ea-4db8-9799-de4963845709

**Comment by Guilouz** [comment]
I think I have fixed it. It will be available in next release.

**Comment by cpasoft** [comment]
> I think I have fixed it. It will be available in next release.

Yes!!!, working fine on v0.3.8-2-g7060f1a9
Thank you!!!...
