### ISSUE TITLE
[BUG] permission level too high

### ISSUE THREAD

**Issue by lin-ycv** [Guilouz/KlipperScreen-Flsun-Speeder-Pad#22]
**Describe the bug**
https://github.com/Guilouz/Klipper-Flsun-Speeder-Pad/discussions/130
Klipperscreen displays the usb disk in print menu using a symbolic link; but the link can be deleted from klipperscreen by clicking the delete button.

**To Reproduce**
1. Go to Print menu
2. Click on the delete button on the USB-Disk folder
3. Symbolic link gets deleted, and future usb drive won't show up when plugged in.

**Expected behavior**
maybe the permissions on the USB-Disk folder should be read only?

**Comment by Guilouz** [comment]
Klippersccren was not developped to print from a USB drive.

It's counterproductive to use external media to print.
