### ISSUE TITLE
Klipperscreen installation permission denied

### ISSUE THREAD

**Issue by ac1dl0rd** [Guilouz/KlipperScreen-Flsun-Speeder-Pad#23]
**Describe the bug**

pi@speeder-pad:~$ cd ~ && git clone https://github.com/Guilouz/KlipperScreen-Flsun-Speeder-Pad.git
Cloning into 'KlipperScreen-Flsun-Speeder-Pad'...
remote: Enumerating objects: 10554, done.
remote: Counting objects: 100% (3873/3873), done.
remote: Compressing objects: 100% (1194/1194), done.
remote: Total 10554 (delta 2412), reused 3685 (delta 2230), pack-reused 6681
Receiving objects: 100% (10554/10554), 9.46 MiB | 2.04 MiB/s, done.
Resolving deltas: 100% (7064/7064), done.
pi@speeder-pad:~$ sudo mv ~/KlipperScreen-Flsun-Speeder-Pad ~/KlipperScreen
[sudo] password for pi:
pi@speeder-pad:~$ ./KlipperScreen/scripts/KlipperScreen-install.sh
-bash: ./KlipperScreen/scripts/KlipperScreen-install.sh: Permission denied

**To Reproduce**

**Expected behavior**

**Screenshots**

**Logfile**
Attach your [klipperscreen.log](https://klipperscreen.readthedocs.io/en/latest/Troubleshooting/)

**Comment by Guilouz** [comment]
Use this:

git clone https://github.com/Guilouz/KlipperScreen-Flsun-Speeder-Pad.git
sudo mv /home/pi/KlipperScreen-Flsun-Speeder-Pad /home/pi/KlipperScreen
cd ~/KlipperScreen
./scripts/KlipperScreen-install.sh

**Comment by AlexRJ30** [comment]
> Use this:
> 
> git clone https://github.com/Guilouz/KlipperScreen-Flsun-Speeder-Pad.git sudo mv /home/pi/KlipperScreen-Flsun-Speeder-Pad /home/pi/KlipperScreen cd ~/KlipperScreen ./scripts/KlipperScreen-install.sh

Thanks @Guilouz but doesn't work too... Permission denied

**Comment by ac1dl0rd** [comment]
Hi Guilouz,

i have try 2 time with fresh 1.2 klipper and same problem
with de speedpad guide and or only klipperscreen guide.

Thank you your help

**Comment by Guilouz** [comment]
You have a permission issue, try this command before to run installer : 

cd ~/KlipperScreen
chmod 755 ./scripts/KlipperScreen-install.sh
