### ISSUE TITLE
Updated Speeder Pad and now this is all that will show on screen.

### ISSUE THREAD

**Issue by pm2clark** [Guilouz/KlipperScreen-Flsun-Speeder-Pad#24]
I apologize if this is the wrong place to ask what I should do to remedy this update. Any assistance would be appreciated and if a fresh install makes it easier then I will do that.

![speederpad error](https://github.com/Guilouz/KlipperScreen-Flsun-Speeder-Pad/assets/62921992/da25e53d-b545-4a7b-a829-6d2702f62af0)

[moonraker.log](https://github.com/Guilouz/KlipperScreen-Flsun-Speeder-Pad/files/12864467/moonraker.log)

**Comment by Guilouz** [comment]
You must enable the 2nd printer in klipperscreen.conf

**Comment by pm2clark** [comment]
This is how it is set as of right now. The Speeder Pad still only shows  the V400. Probably just going to do a fresh install so I dont have to keep bothering you.

###############################
# Multiple Instances Settings
########################################

# For Multi Instances using, uncomment and edit lines you need by removing the '#' symbol.

# If multiple printers are defined, this can be set the name of the one to show at startup.
[main]

printer: FLSUN V400
printer: SR

########################################
# Printer 1 Settings
########################################

# Define printer name. Name is anything after the first printer word.
[printer FLSUN V400]

# Define the moonraker host/port if different from 127.0.0.1 and 7125.
moonraker_host: 192.168.1.54
moonraker_port: 7125

# Override the movement speed and set a specific for this printer.
# These setting overrides the settings configured in the UI. If specified,
# the values configured in the UI will not be used.
move_speed_xy: 80
move_speed_z: 80

# Define distances and speeds for the extrude panel.
extrude_distances: 5, 10, 15, 25
extrude_speeds: 1, 2, 5, 10

# Camera configuration
#camera_url: http://127.0.0.1/webcam/?action=stream


########################################
# Printer 2 Settings
########################################

# For Multi Instances using, uncomment and edit lines you need by removing the '#' symbol.

# Define printer name. Name is anything after the first printer word.
[printer SR]

# Define the moonraker host/port if different from 127.0.0.1 and 7125.
moonraker_host: 192.168.1.53
moonraker_port: 7126

# Override the movement speed and set a specific for this printer.
# These setting overrides the settings configured in the UI. If specified,
# the values configured in the UI will not be used.
#move_speed_xy: 80
#move_speed_z: 80

# Define distances and speeds for the extrude panel.
#extrude_distances: 5, 10, 15, 25
#extrude_speeds: 1, 2, 5, 10

# Camera configuration
#camera_url: http://127.0.0.1/webcam/?action=stream

**Comment by deddroid** [comment]
hi,

same problem for me, but replace the klipperscreen.conf with the new one didn't work for me.

also tryed to remove all files and replace all togheter with new download, but same problem

**Comment by deddroid** [comment]
didn't work, but thanks for your answer. I'll try to redeploy the speederpad with your guide
