### ISSUE TITLE
FLSUN logo on zbolt red and blue theme

### ISSUE THREAD

**Issue by ManuMod** [Guilouz/KlipperScreen-Flsun-Speeder-Pad#27]
Hello,

There is the Bigtreetech PAD7 logo in background with the z-bolt-blue and red klipperScreen theme. I think it would be better for this repo to use the good klipper.svg like z-bolt and material-blue/red.

I prefer the blue below the buttons and I modifyed it for me ;-)

**Comment by Guilouz** [comment]
Because that theme I use for by BTT Pad^^

**Comment by ManuMod** [comment]
I kinda suspected that, lol.

Perhaps, it would be better if we rename z-bolt in zbolt-FLSUN-red, zbolt-blue/red in z-bolt-BTT-blue/red and create a z-bolt-FLSUN-blue or something like this and everybody is happy ;-).

I would like to take this opportunity to thank you once again for your sharing.

**Comment by Guilouz** [comment]
I have updated icons
