### ISSUE TITLE
[BUG MCU]

### ISSUE THREAD

**Issue by Flazor-sun** [Guilouz/KlipperScreen-Flsun-Speeder-Pad#28]
Bonjour,

J'ai fait le mise à jour vers votre firmware en suivant à la lettre les explications mais une fois terminée, après avoir importer les fichiers de config dans Mainsail et modifié l'ID MCU avec celui donner en SSH. J'ai eu le défaut MCU enable to connect et j'ai remarqué que je n'ai plus la section MCU dans l'onglet Machine sous System Load, je ne vois plus sa version... comme le montre la photo ci-dessous.

![Defaut_mcu](https://github.com/Guilouz/KlipperScreen-Flsun-Speeder-Pad/assets/121314487/8585abdf-ce9a-44fd-abc9-367c7eb07f37)

J'ai donc essayé de revenir sur le firmware original avec le flash de l'écran mais comme je m'y attendais, ça n'a pas réglé le problème.
Auriez vous une idée car j'ai cherché sur plusieurs forum et fait plusieurs essais sans résultat.

Dans l'attente de votre réponse, merci d'avance.

Cordialement.

**Comment by Miko91330** [comment]
Bonjour,

J'ai le même problème et j'ai aussi essayer le flash de l'écran . Avez vous pu identifié le soucis?

**Comment by Flazor-sun** [comment]
Bonjour,

Je pense avoir compris que ça vient bien du flash. Malgré que le fichier soit bien pris en compte, le flash ne s'effectue pas complètement pour je ne sais quelle raison.
Donc non j'ai pas encore de solution, je me suis rapproché de FLSUN et suis dans l'attente d'une réponse. Lorsque j'aurais plus d'informations je vous en ferai part.
Sur l'autre V400 j'ai une mis une carte mère bigthree skr 3 et là pas de problème pour le flash car le processeur de la carte mère est bien dans la liste.
