### ISSUE TITLE
[BUG]Unable to install

### ISSUE THREAD

**Issue by lin-ycv** [Guilouz/KlipperScreen-Flsun-Speeder-Pad#29]
**Describe the bug**
During `KlipperScreen-install.sh`, pad ssh will disconnect and stop functioning
https://github.com/Guilouz/Klipper-Flsun-Speeder-Pad/discussions/151

**To Reproduce**
Follow the steps in wiki:
https://github.com/Guilouz/Klipper-Flsun-Speeder-Pad/wiki
on the step `Install-Official-Builds-(1-instance)`
`KlipperScreen-install.sh` will not finish

**Expected behavior**
install klipperscreen

**Logfile**
Pad bricks itselve, unable to ssh to get logs

**Comment by Wrathlord12** [comment]
meme erreu que vous

**Comment by SquirmN** [comment]
Same issue, but noticed it has stopped at the iptables part of the install. I tried single and multi with it freezing at the same spot for iptables.  I am able to reflash back to v1.2 firmware and start over.

**Comment by lin-ycv** [comment]
> reflash back to v1.2 firmware and start over.
But the same issue would occur when installing this, did you install klipperscreen through kiauh instead?

**Comment by SquirmN** [comment]
Sorry for the confusion, I am just reinstalling the rooted v1.2 image back onto the speed-pad and starting over.  I use kiauh to remove klipperscreen from the v1.2 build and then follow the steps from Guilouz documented installation steps.

**Comment by Guilouz** [comment]
You can now use this command to install KlipperScreen without network manager:

```
 ./KlipperScreen/scripts/KlipperScreen-install-fix.sh
 ```

**Comment by Maggan0** [comment]
May I ask what was the problem?
Just for better understanding of the system and for possible future problems with Klipper and/or Klipper screen.

**Comment by SquirmN** [comment]
problem was with the network-manager in the install script, it would freeze at iptables update part.  I edited out as it was posted in the pull request and it fixed the install issue.

**Comment by kleinwareio** [comment]
Just ran into this 10 minutes ago. Last log line is

```
update-alternatives: using /usr/sbin/iptables-legacy to provide /usr/sbin/iptables (iptables) in auto mode

Network error: Software caused connection abort
```

I'll re-flash and run through all the steps again, but this time try again with `KlipperScreen-install-fix`.

Given that this _just happened_ with a fresh pull, I'm not sure this issue is really "Closed."

---

p.s. Thanks for putting all this together! I bought you a Ko-Fi as I really appreciate how much time you've saved me!
