### ISSUE TITLE
Black screen after updating to latest screen version

### ISSUE THREAD

**Issue by Naninani** [Guilouz/KlipperScreen-Flsun-Speeder-Pad#3]
Just updated to latest and the screen turned black. 

Rebooted but still the same. Is there a way to revert to the previous version?

![422AD197-C977-4AE5-B2D2-B715B84FCA83](https://user-images.githubusercontent.com/1681582/200449496-40b2fa46-4f97-41cb-8b3d-e2556f9e5aaa.jpeg)
![7FDABF75-FED4-4946-BFC7-C9D974798DF9](https://user-images.githubusercontent.com/1681582/200449502-54363f9c-5bb9-4a88-aa30-a380ca23e63e.jpeg)

**Comment by Guilouz** [comment]
Fixed with v0.2.6-88. Update again.
