### ISSUE TITLE
Klipperscreen "Move" menu has a "50" instead of "5" and therefore cannot move in 5 increments

### ISSUE THREAD

**Issue by CaryBab** [Guilouz/KlipperScreen-Flsun-Speeder-Pad#31]
**Describe the bug**
Klipperscreen "Move" menu has a "50" instead of "5" and therefore cannot move in 5 increments

**To Reproduce**
1. Go to Move menu and you will see it.
2. If you press it, moves you cursor over to "50" and selects it.

**Expected behavior**
Have the ability to move in 5 increments

**Comment by Guilouz** [comment]
Fixed.
