### ISSUE TITLE
Problème installation KlipperScreen pour FLSUN Speeder Pad

### ISSUE THREAD

**Issue by JYCrois** [Guilouz/KlipperScreen-Flsun-Speeder-Pad#32]
Bonjour,

au moment de reinstaller KlipperScreen l'installation plante à ce niveau :

Setting up libhttp-negotiate-perl (6.01-1) ...
Setting up libhttp-cookies-perl (6.08-1) ...
Setting up iptables (1.8.4-3ubuntu2.1) ...
update-alternatives: using /usr/sbin/iptables-legacy to provide /usr/sbin/iptables (iptables) in auto mode
update-alternatives: using /usr/sbin/ip6tables-legacy to provide /usr/sbin/ip6tables (ip6tables) in auto mode

Network error: Software caused connection abort

Je suis obligé de recommencer toute la procédure d'installation depuis le début, j'ai fais 5 essais mais toujour le même résultat.

Pour information j'ai déjà effectué votre installation sur 2 Flsun V400 pour des amis sans aucun problème.

J'ai l'impression que le serveur coupe la connection à un moment de l'installation.

Enespérent que vous aurez une solution et en vous remerciant pour votre travail.

Cordialement,

**Comment by Guilouz** [comment]
Lis le wiki, la solution y est.

**Comment by JYCrois** [comment]
> Voici le wiki, la solution et est.

Pardon, je ne comprends pas votre réponse

**Comment by Guilouz** [comment]
https://github.com/Guilouz/Klipper-Flsun-Speeder-Pad/wiki/Install-Official-Builds-(1-instance)

**Comment by JYCrois** [comment]
> https://github.com/Guilouz/Klipper-Flsun-Speeder-Pad/wiki/Install-Official-Builds-(1-instance)

Merci pour ton retour, j'ai pu finir l'installation, tout fonctionne correctement je n'ai qu'un seul problème, ma caméra ne fonctionne pas, elle fonctionne très bien avant d'installer les version officielles mais maintenant sous crowsnest rien à faire, pourtant je n'ai aucune erreur tout est à jour (voir PJ), aurais-tu une idée ? si vraiment il n'y a pas de solution pour crowsnest est-il possible de réinstaller MPG-Streamer et comment (je n'ai pas vu l'option dans KIAUH) ? cordialement,
![Crowsnest conf](https://github.com/Guilouz/KlipperScreen-Flsun-Speeder-Pad/assets/116349530/ec724961-18b2-40f9-bbb6-0ad421659616)
![Gestionnaire de mise à jour](https://github.com/Guilouz/KlipperScreen-Flsun-Speeder-Pad/assets/116349530/05f8dc48-3159-48b4-9e2e-f8bbc9ec496f)
![moonraker conf](https://github.com/Guilouz/KlipperScreen-Flsun-Speeder-Pad/assets/116349530/7d865b4e-9c32-48e1-824a-855ea3474185)
![réglage caméra](https://github.com/Guilouz/KlipperScreen-Flsun-Speeder-Pad/assets/116349530/8849ab9b-107c-407a-8410-998c48a21bd8)

**Comment by aznnomness** [comment]
I am also experiencing this issue.

```Setting up libmbim-proxy (1.26.2-1~ubuntu20.04.1) ...
Setting up fonts-ipafont (00303-18ubuntu1) ...
Setting up network-manager-pptp (1.2.8-2) ...
Setting up libmpv1:armhf (0.32.0-1ubuntu1) ...
Setting up libfile-desktopentry-perl (0.22-1) ...
Setting up mpv (0.32.0-1ubuntu1) ...
Setting up libnetfilter-conntrack3:armhf (1.0.7-2) ...
Setting up libio-socket-ssl-perl (2.067-1) ...
Setting up libhttp-message-perl (6.22-1) ...
Setting up libhtml-form-perl (6.07-1) ...
Setting up libfile-mimeinfo-perl (0.29-1) ...
Setting up libmpv-dev:armhf (0.32.0-1ubuntu1) ...
Setting up libhttp-negotiate-perl (6.01-1) ...
Setting up libhttp-cookies-perl (6.08-1) ...
Setting up iptables (1.8.4-3ubuntu2.1) ...
update-alternatives: using /usr/sbin/iptables-legacy to provide /usr/sbin/iptables (iptables) in auto mode
client_loop: send disconnect: Broken pipe
```

I cannot SSH back into the speeder pad and rebooting the speeder pad causes it to lock up during boot. Looks to be related to installing the optional packages.

**Comment by Guilouz** [comment]
Already answered, fix is on the wiki.

**Comment by aznnomness** [comment]
I didn't understand your comment with the fix, I understood soon after I posted the message. Thank you!
