### ISSUE TITLE
[EN] Temperature colors and graphs

### ISSUE THREAD

**Issue by Winky1st** [Guilouz/KlipperScreen-Flsun-Speeder-Pad#35]
**Is your feature request related to a problem? Please describe.**
NO

**Describe the solution you'd like**
Would it be feasible  to auto match temperature colors on klipperscreen to the one choosen on mainsail?
So labels and graphs will be identical colors.... isnt it cool ?

**Additional context**
Cheers :)

**Comment by Guilouz** [comment]
Colors can’t be synchronized. Must be set on each side.
