### ISSUE TITLE
typo in /ks_includes/defaults.conf -> "extrudde" instead of "extrude' [BUG]

### ISSUE THREAD

**Issue by h3rm** [Guilouz/KlipperScreen-Flsun-Speeder-Pad#36]
**Describe the bug**
there is a typo in row 258-> "extrudde" instead of "extrude" which causes a PixbufFromFile error in klipperscreen.log because there is no "extrudde.svg" file in /home/pi/KlipperScreen/styles/z-bolt/images/

_[menu __print extrude]
name: {{ gettext('Extrude') }}
icon: extrudde
panel: extrude
enable: {{ printer.extruders.count > 0 }}_

**To Reproduce**
1. open KlipperScreen-Flsun-Speeder-Pad/ks_includes/ in your git
2. Click on 'defaults.conf' 'row 258'
4. See error in klipperScreen.log

**Expected behavior**
correct icon filename in defaults.conf so that the the PixbufFromFile error in klipperscreen.log is gone:

  _File "/home/pi/KlipperScreen/ks_includes/KlippyGtk.py", line 134, in PixbufFromFile
    return GdkPixbuf.Pixbuf.new_from_file_at_size(filename, int(width), int(height))
gi.repository.GLib.GError: g-file-error-quark: Failed to open file “/home/pi/KlipperScreen/styles/z-bolt/images/extrudde.svg”: No such file or directory (4)_

**Screenshots**
![2024-02-25 13_08_25-KlipperScreen-Flsun-Speeder-Pad_ks_includes_defaults conf at master · Guilouz_Kl](https://github.com/Guilouz/KlipperScreen-Flsun-Speeder-Pad/assets/9608955/6302bf56-a991-45c5-904d-a4dfd08cfef5)

![2024-02-25 13_08_03-v400 – Mozilla Firefox](https://github.com/Guilouz/KlipperScreen-Flsun-Speeder-Pad/assets/9608955/a964fea3-5cc5-4aa0-9859-fd71904303ea)
![2024-02-25 13_17_49-v400 – Mozilla Firefox](https://github.com/Guilouz/KlipperScreen-Flsun-Speeder-Pad/assets/9608955/5abdfd42-8659-4cd9-9d8c-23219dd207b8)

![2024-02-25 13_11_30-192 168 0 73 (pi)](https://github.com/Guilouz/KlipperScreen-Flsun-Speeder-Pad/assets/9608955/33e997ee-7672-48ee-9f4a-59f5ee85bc76)

**Logfile**
Attach your [klipperscreen.log]:
[KlipperScreen.log](https://github.com/Guilouz/KlipperScreen-Flsun-Speeder-Pad/files/14396319/KlipperScreen.log)

**Comment by Guilouz** [comment]
Thanks, it's fixed.
