### ISSUE TITLE
[BUG] Typo in temperature.py

### ISSUE THREAD

**Issue by martin-hei** [Guilouz/KlipperScreen-Flsun-Speeder-Pad#38]
**Describe the bug**
KlipperScreen crashes on the temperature panel

-> There is a typo in /panels/temperature.py in line 331: "sself" should be "self"
![image](https://github.com/Guilouz/KlipperScreen-Flsun-Speeder-Pad/assets/33435204/30120eff-cddb-4b7a-bb82-4810dba9eef7)

**To Reproduce**
1. Go to 'Main Panel'
2. Click on 'Temperature'

**Expected behavior**
The temperature panel shows up

**Screenshots**
![image](https://github.com/Guilouz/KlipperScreen-Flsun-Speeder-Pad/assets/33435204/34a32eb0-5054-4ad9-bdeb-14648838762c)

**Logfile**
[KlipperScreen.log](https://github.com/Guilouz/KlipperScreen-Flsun-Speeder-Pad/files/14735857/KlipperScreen.log)

**Comment by Guilouz** [comment]
Fixed.

**Comment by martin-hei** [comment]
Thanks Cyril, that was faster than it took me to open the issue :-)
