### ISSUE TITLE
[BUG]  v0.3.9-19 > v0.3.9-20 repo is corrupt

### ISSUE THREAD

**Issue by Winky1st** [Guilouz/KlipperScreen-Flsun-Speeder-Pad#39]
**Describe the bug**
searching for updates  v0.3.9-19 > v0.3.9-20 pops out a message "repo is corrupt"

**To Reproduce**
1. Go to 'Machine Tab'
2. Click on 'Update '

Thank you Cyril for fix.

**Comment by Guilouz** [comment]
Can i have a screenshot of this error

**Comment by Winky1st** [comment]
Sadly no!  by mistake and my stupidity, I clicked on update all (not on hard update on specific klipperscreen line) and it updated to -20 and label disappeared. The label was orange color under the klipperscreen line :(I hope not to have made something by bad to my installation. Sorry bro can’t help on thatTesto Inviato da dispositivo mobile, prego scusare le abbreviazioni ed eventuali errori di battitura.Il giorno 9 apr 2024, alle ore 00:48, Cyril Guislain ***@***.***> ha scritto:﻿
Can i have a screenshot of this error

**Comment by Guilouz** [comment]
So it’s an issue on your side, on your installation.
That’s means your local repo was not equal to remote repo.
