### ISSUE TITLE
[BUG] Klipperscreen and moonraker 15-07-2024

### ISSUE THREAD

**Issue by limeprod** [Guilouz/KlipperScreen-Flsun-Speeder-Pad#46]
**Describe the bug**
After last update of moonraker and klipperscreen (by web interface), i have no screen on pad (like blank screensaver) and no http page. SSH connection is OK
Sorry for my english translate

**To Reproduce**
Update by web interface

**Logfile**
[moonraker.log](https://github.com/user-attachments/files/16230821/moonraker.log)
[klippy.log](https://github.com/user-attachments/files/16230979/klippy.log)

**Comment by Guilouz** [comment]
There is no issue with latest update, Tested and working fine.

**Comment by limeprod** [comment]
Hello, 
a good occasion to reinstall all and in fact is ok 
sorry ;-)
