### ISSUE TITLE
[BUG] Wifi needs to reconnect using speederpad on cold boot

### ISSUE THREAD

**Issue by lin-ycv** [Guilouz/KlipperScreen-Flsun-Speeder-Pad#47]
**Describe the bug**
after a complete clean install following the wiki instructions. wifi does not work after boot.
On boot the printer shows itself as being connected to the ap and even shows an ip address, but I cannot access mainsail and ssh.
I have to go into klipper screen, open network and click on the wifi ssid again to connect.
https://github.com/Guilouz/Klipper-Flsun-Speeder-Pad/discussions/178#discussioncomment-10007970

also that the network menu on klipperscreen is quite laggy/slow compared to all the other menus

**To Reproduce**
1. Shutoff printer completely
2. wait for a while (an hour? next day?)
3. boot up printer
4. try to ssh or access mainsail

not sure why, but reboot commands don't create this issue, boot up shortly after shutdown also doens't create this issue.

**Expected behavior**
wifi should work after boot

**Logfile**
[KlipperScreen.log](https://github.com/user-attachments/files/16243819/KlipperScreen.log)

**Additional information**
I have static IP set for the printer on my AP, not sure if that makes a difference

**Comment by Guilouz** [comment]
Can’t reproduce issue on my 2 pads and this is not related to Klipperscreen, it’s looks like a network issue.

**Comment by lin-ycv** [comment]
Any steps I can do to debug this issue? 
All my other devices on the network have no issues like this. 
When I was on the flsun firmware, I also did not encounter this issue.
