### ISSUE TITLE
Error on Kleeper Recovery

### ISSUE THREAD

**Issue by Liight07** [Guilouz/KlipperScreen-Flsun-Speeder-Pad#5]
Hello, 
Thanks for your hard word. 

I proceed to the upgrade with the help of your tutorial. But I have something strange. When I put the code in the mooraker.conf, save it and restart, my KlipperScreen turn "INVALID" with a red button. Not yellow with "DIRTY"

I tried the "Hard recovery" thing, but I have an error. 
![Error KLIPPER](https://user-images.githubusercontent.com/119060295/204005306-c0179148-8c75-48e1-8d2d-e71c582b8147.PNG)

I tried to restore my backup mooraker.conf and the same error occured.

Do you have any idea to help me with my issue ?
Thanks :)

**Comment by Ghenghis** [comment]
I have the same issue. Removed the klipperscreen using kiauh a couple times. Getting same issue.
![20221127_163158](https://user-images.githubusercontent.com/6685932/204165738-89793c35-45d7-41c9-8e5a-764b723a075a.jpg)

**Comment by Guilouz** [comment]
Make sure you have deleted .gitconfig file.

sudo rm /home/pi/.gitconfig

**Comment by Ghenghis** [comment]
> Make sure you have deleted .gitconfig file.
> 
> sudo rm /home/pi/.gitconfig

Thank you very much! Hats off to you Sir!
![20221128_124140](https://user-images.githubusercontent.com/6685932/204366417-e3bd3b50-a61a-445a-a340-b22b82dcb34e.jpg)
Worked like a charm.

**Comment by Liight07** [comment]
> Make sure you have deleted .gitconfig file.
> 
> sudo rm /home/pi/.gitconfig

Thanks a lot ! I even didn't get any error message on the KlipperScreen version (no DITY stuff). Actually with this version of KlipperScreen v0.2.9-9-g85be655
Is it the right one ?

**Comment by Guilouz** [comment]
This command is on my github, it means that you did not follow the tutorial to the letter^^

 Yes it is the last version.
