### ISSUE TITLE
What happend to the Calibration Screen?

### ISSUE THREAD

**Issue by MrBaham** [Guilouz/KlipperScreen-Flsun-Speeder-Pad#9]
First there is a Buttons missing on the Calibration Screen. There is no Button for the Z-Offset.

Second, when i press the Multiple Calibrations button and then the Start Button and then the Z-Offset Button, there is an Error.

I can not set the Z-Offset

![20230220_175437](https://user-images.githubusercontent.com/54911161/220165931-306e2bdd-7550-4638-9a27-a9d8b6ab8df2.jpg)
![20230220_175529](https://user-images.githubusercontent.com/54911161/220165938-88700cbf-9b42-4f29-9526-2137755fa926.jpg)
![20230220_175544](https://user-images.githubusercontent.com/54911161/220165925-9ee5ec98-e3f6-44f3-b76f-c0278506e45e.jpg)

**Comment by Guilouz** [comment]
You have not updated your configuration files. Please check my Github page.
